import "./globals.css";
import { Fira_Code } from "next/font/google";

const fira_Code = Fira_Code({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${fira_Code.className} h-[100vh]`}>
                {children}
            </body>
        </html>
    );
}
